version: 1.0

description: Build Scout load config from samples

input:
  - sample_ids
  - pipeline
  - pipeline_dir

vars:
  - samples: []

output:
  - load_config_path: <% ctx(load_config_path) %>

tasks:
  get_samples:
    with: sample_id in <% ctx(sample_ids) %>
    action: igene.get_sample
    input:
      sample_id: <% item(sample_id) %>
    next:
      - when: <% succeeded() %>
        publish:
          - samples: <% result().select($.body) %>
        do:
          - generate_load_config

  generate_load_config:
    action: scout.generate_load_config
    input:
      samples: <% ctx(samples) %>
      pipeline_dir: <% ctx(pipeline_dir) %>
      pipeline: <% ctx(pipeline) %>
    next:
      - when: <% succeeded() %>
        publish:
          - load_config_path: <% result().config_path %>
        do:
          - load_case

  load_case:
    action: gmc_norr_scout.load_case
    input:
      hosts: <% ctx(scout_host) %>
      load_config: <% ctx(load_config_path) %>
      container_name: <% ctx(container_name) %>