---
scout_host:
  description: Host machine for scout
  type: string
  required: true

scout_cwd:
  description: working directory on scout host
  type: string
  required: true

loqusdb_config_map:
  description: mapping analysis pipeline to config file mounted in docker container
  type: object
  required: true

loqusdb_ped:
  description: subdir and suffix for ped file to be used by loqusdb
  type: object
  required: true

loqusdb_vcf:
  description: subdir and suffix for vcf file to be used by loqusdb
  type: object
  required: true
